

module Lambda.Abs where

-- Haskell module generated by the BNF converter




newtype Ident = Ident String deriving (Eq, Ord, Show, Read)
data Expr
    = ELam Ident Expr
    | ELet Ident Expr Expr
    | EApp Expr Expr
    | EVar Ident
    | EILit Integer
  deriving (Eq, Ord, Show, Read)

