module Lambda.Skel where

-- Haskell module generated by the BNF converter

import Lambda.Abs
import Lambda.ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transIdent :: Ident -> Result
transIdent x = case x of
  Ident string -> failure x
transExpr :: Expr -> Result
transExpr x = case x of
  ELam ident expr -> failure x
  ELet ident expr1 expr2 -> failure x
  EApp expr1 expr2 -> failure x
  EVar ident -> failure x
  EILit integer -> failure x
  EDLit double -> failure x

